import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
    darkMode: ["variant", '[data-theme="dark"] &'],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-dm-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-dm-mono)", "monospace"],
      },
      colors: {
        "neutral-primary-soft": "var(--card)",
        "neutral-primary": "var(--bg2)",
        "neutral-primary-medium": "var(--bg3)",
        "neutral-primary-strong": "var(--bg3)",
        "neutral-secondary-soft": "var(--card)",
        "neutral-secondary": "var(--bg2)",
        "neutral-secondary-medium": "var(--bg3)",
        "neutral-secondary-strong": "var(--bg3)",
        "neutral-tertiary-soft": "var(--bg3)",
        "neutral-tertiary": "var(--bg3)",
        "neutral-tertiary-medium": "var(--bg3)",
        "neutral-quaternary": "var(--border)",
        "quaternary-medium": "var(--ink3)",
        "gray": "var(--ink3)",
        "brand-softer": "var(--accentbg)",
        "brand-soft": "var(--accentbg)",
        "brand": "var(--accent)",
        "brand-medium": "var(--accent)",
        "brand-strong": "var(--accent)",
        "success-softer": "var(--successbg)",
        "success-soft": "var(--successbg)",
        "success": "var(--success)",
        "success-medium": "var(--success)",
        "success-strong": "var(--success)",
        "danger-soft": "var(--accentbg)",
        "danger": "#DC2626",
        "danger-medium": "#B91C1C",
        "danger-strong": "#991B1B",
        "warning-soft": "#FFFBEB",
        "warning": "#D97706",
        "warning-medium": "#B45309",
        "warning-strong": "#92400E",
        "dark": "var(--ink)",
        "dark-strong": "var(--ink)",
        "disabled": "var(--bg3)",
        "heading": "var(--ink)",
        "body": "var(--ink2)",
        "body-subtle": "var(--ink3)",
        "fg-brand": "var(--accent)",
        "fg-brand-strong": "var(--accent)",
        "fg-brand-subtle": "var(--accent)",
        "fg-success": "var(--success)",
        "fg-success-strong": "var(--success)",
        "fg-danger": "#DC2626",
        "fg-danger-strong": "#B91C1C",
        "fg-warning": "#D97706",
        "fg-warning-subtle": "#D97706",
        "fg-disabled": "var(--ink3)",
        "fg-yellow": "#CA8A04",
        "fg-info": "#2563EB",
        "fg-purple": "#7C3AED",
        "fg-purple-strong": "#6D28D9",
        "fg-cyan": "#0891B2",
        "fg-indigo": "#4F46E5",
        "fg-pink": "#DB2777",
        "fg-lime": "#65A30D",
        "border-buffer": "var(--card)",
        "border-buffer-medium": "var(--bg2)",
        "border-buffer-strong": "var(--bg3)",
        "border-muted": "var(--bg3)",
        "border-light-subtle": "var(--border)",
        "border-light": "var(--border)",
        "border-light-medium": "var(--border)",
        "border-default-subtle": "var(--border)",
        "border-default": "var(--border)",
        "border-default-medium": "var(--border)",
        "border-default-strong": "var(--ink3)",
        "border-success-subtle": "var(--successbd)",
        "border-success": "var(--successbd)",
        "border-danger-subtle": "#FECACA",
        "border-danger": "#DC2626",
        "border-warning-subtle": "#FDE68A",
        "border-warning": "#D97706",
        "border-brand-subtle": "var(--accentbd)",
        "border-brand": "var(--accent)",
        "border-brand-light": "var(--accent)",
        "border-dark-subtle": "var(--ink3)",
      },
      borderRadius: {
        "base": "12px",
        "DEFAULT": "6px",
        "sm": "4px",
        "full": "9999px",
      },
      boxShadow: {
        "2xs": "0 1px rgb(0 0 0 / 0.04)",
        "xs": "0 1px 2px 0 rgb(0 0 0 / 0.04)",
        "sm": "0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.06)",
        "md": "0 4px 6px -1px rgb(0 0 0 / 0.07), 0 2px 4px -2px rgb(0 0 0 / 0.05)",
        "lg": "0 10px 15px -3px rgb(0 0 0 / 0.08), 0 4px 6px -4px rgb(0 0 0 / 0.04)",
        "xl": "0 20px 25px -5px rgb(0 0 0 / 0.08), 0 8px 10px -6px rgb(0 0 0 / 0.04)",
        "2xl": "0 25px 50px -12px rgb(0 0 0 / 0.15)",
      },
    },
  },
  plugins: [],
};

export default config;

