// ═══════════════════════════════════════════════════════════════════
//  TOOL REGISTRY — Single Source of Truth
//  To add a new tool: add one entry to `registryEntries` below.
//  Everything else (routes, SEO, metadata, OG, JSON-LD, breadcrumbs,
//  internal links, related tools, static generation) is automatic.
// ═══════════════════════════════════════════════════════════════════

import { generateToolContent } from "@/lib/content-generator";

// ── Types ─────────────────────────────────────────────────────────

export type Engine = "image" | "document" | "video" | "audio" | "text" | "data" | "archive";
export type ProcessingType = "image" | "document" | "video" | "audio" | "other" | "archive";

export interface FormatDefinition {
  ext: string;
  name: string;
  fullName: string;
  mime: string;
  description: string;
  family: string;
  popular: boolean;
}

export interface ToolSeo {
  title: string;
  description: string;
  keywords: string[];
}

export interface ToolFaqEntry {
  q: string;
  a: string;
}

export interface ToolCategory {
  id: string;
  slug: string;
  name: string;
  description: string;
  shortDescription: string;
  icon: string;
  seo: { title: string; description: string };
}

/** Single entry in the tool registry — the ONLY thing to edit */
export interface RegistryEntry {
  slug: string;
  name: string;
  category: string;
  inputFormats: string[];
  outputFormats: string[];
  engine: Engine;
  popular?: boolean;
  comingSoon?: boolean;
  autoGenerated?: boolean;
  seo?: Partial<ToolSeo>;
  faq?: ToolFaqEntry[];
}

export interface ToolContent {
  h1: string;
  introduction: string;
  howToGuide: { step: number; title: string; description: string }[];
  benefits: { title: string; description: string }[];
  useCases: { title: string; description: string }[];
}

export interface ToolDefinition {
  id: string;
  slug: string;
  name: string;
  shortName: string;
  title: string;
  description: string;
  longDescription: string;
  categoryId: string;
  inputFormat: FormatDefinition;
  outputFormat: FormatDefinition | null;
  inputFormats: string[];
  outputFormats: string[];
  engine: Engine;
  processingType: ProcessingType;
  popular: boolean;
  comingSoon: boolean;
  seo: ToolSeo;
  faq: ToolFaqEntry[];
  relatedSlugs: string[];
  content: ToolContent;
}

// ── Format Registry ──────────────────────────────────────────────

export const FORMATS: Record<string, FormatDefinition> = {
  png:   { ext: "png",   name: "PNG",   fullName: "Portable Network Graphics",              mime: "image/png",           description: "lossless image format with transparency support",              family: "raster", popular: true },
  jpg:   { ext: "jpg",   name: "JPG",   fullName: "JPEG Image",                             mime: "image/jpeg",          description: "widely compatible lossy format for photographs",               family: "raster", popular: true },
  jpeg:  { ext: "jpeg",  name: "JPEG",  fullName: "JPEG Image",                             mime: "image/jpeg",          description: "widely compatible lossy format for photographs",               family: "raster", popular: false },
  webp:  { ext: "webp",  name: "WebP",  fullName: "WebP Image Format",                      mime: "image/webp",          description: "modern format with superior compression from Google",           family: "raster", popular: true },
  gif:   { ext: "gif",   name: "GIF",   fullName: "Graphics Interchange Format",            mime: "image/gif",           description: "supports basic animations and transparency",                   family: "raster", popular: true },
  bmp:   { ext: "bmp",   name: "BMP",   fullName: "Bitmap Image File",                      mime: "image/bmp",           description: "uncompressed raster format with large file sizes",              family: "raster", popular: false },
  svg:   { ext: "svg",   name: "SVG",   fullName: "Scalable Vector Graphics",               mime: "image/svg+xml",       description: "resolution-independent vector format for icons and graphics",   family: "vector", popular: true },
  ico:   { ext: "ico",   name: "ICO",   fullName: "Icon Format",                            mime: "image/x-icon",        description: "small format used for website favicons",                       family: "raster", popular: false },
  avif:  { ext: "avif",  name: "AVIF",  fullName: "AV1 Image File Format",                  mime: "image/avif",          description: "next-gen compression format based on AV1 video codec",          family: "raster", popular: false },
  tiff:  { ext: "tiff",  name: "TIFF",  fullName: "Tagged Image File Format",               mime: "image/tiff",          description: "high-quality format preferred in printing and publishing",      family: "raster", popular: false },
  heic:  { ext: "heic",  name: "HEIC",  fullName: "High Efficiency Image Format",            mime: "image/heic",          description: "modern Apple image format with superior compression",           family: "raster", popular: true },
  pdf:   { ext: "pdf",   name: "PDF",   fullName: "Portable Document Format",               mime: "application/pdf",     description: "universal document format for sharing and printing",           family: "document", popular: true },
  doc:   { ext: "doc",   name: "DOC",   fullName: "Word Document (Legacy)",                 mime: "application/msword",  description: "legacy Microsoft Word format",                                family: "document", popular: false },
  docx:  { ext: "docx",  name: "DOCX",  fullName: "Word Document",                          mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", description: "modern Microsoft Word format",                                 family: "document", popular: true },
  txt:   { ext: "txt",   name: "TXT",   fullName: "Plain Text",                             mime: "text/plain",          description: "universal text format with no formatting",                     family: "text", popular: true },
  html:  { ext: "html",  name: "HTML",  fullName: "HyperText Markup Language",              mime: "text/html",           description: "web page format with markup structure",                        family: "markup", popular: false },
  md:    { ext: "md",    name: "MD",    fullName: "Markdown",                               mime: "text/markdown",       description: "lightweight markup language for formatted text",               family: "markup", popular: false },
  rtf:   { ext: "rtf",   name: "RTF",   fullName: "Rich Text Format",                      mime: "application/rtf",     description: "formatted text document format",                               family: "document", popular: false },
  csv:   { ext: "csv",   name: "CSV",   fullName: "Comma-Separated Values",                 mime: "text/csv",            description: "tabular data format using commas as delimiters",               family: "data", popular: true },
  json:  { ext: "json",  name: "JSON",  fullName: "JavaScript Object Notation",             mime: "application/json",    description: "structured data interchange format",                           family: "data", popular: false },
  xml:   { ext: "xml",   name: "XML",   fullName: "eXtensible Markup Language",             mime: "application/xml",     description: "structured document markup format",                            family: "data", popular: false },
   mp4:   { ext: "mp4",   name: "MP4",   fullName: "MPEG-4 Video",                           mime: "video/mp4",           description: "most widely compatible digital video format",                  family: "video", popular: true },
   webm:  { ext: "webm",  name: "WebM",  fullName: "WebM Video",                             mime: "video/webm",          description: "royalty-free web-optimized video format",                      family: "video", popular: true },
   avi:   { ext: "avi",   name: "AVI",   fullName: "Audio Video Interleave",                 mime: "video/x-msvideo",     description: "legacy Microsoft multimedia container format",                 family: "video", popular: false },
   mov:   { ext: "mov",   name: "MOV",   fullName: "QuickTime Movie",                        mime: "video/quicktime",     description: "Apple multimedia container format",                            family: "video", popular: false },
   mkv:   { ext: "mkv",   name: "MKV",   fullName: "Matroska Video",                         mime: "video/x-matroska",    description: "flexible open-source multimedia container",                     family: "video", popular: false },
   m4v:   { ext: "m4v",   name: "M4V",   fullName: "MPEG-4 Video (Apple)",                   mime: "video/x-m4v",         description: "Apple variant of MPEG-4 video format",                         family: "video", popular: false },
   mpeg:  { ext: "mpeg",  name: "MPEG",  fullName: "MPEG-1/2 Video",                         mime: "video/mpeg",          description: "legacy video compression standard",                            family: "video", popular: false },
   ogv:   { ext: "ogv",   name: "OGV",   fullName: "Ogg Video",                              mime: "video/ogg",           description: "free open-source video container format",                      family: "video", popular: false },
   "3gp": { ext: "3gp",   name: "3GP",   fullName: "3GPP Multimedia",                        mime: "video/3gpp",          description: "mobile-optimized video format",                                family: "video", popular: false },
   flv:   { ext: "flv",   name: "FLV",   fullName: "Flash Video",                            mime: "video/x-flv",         description: "Adobe Flash video format used for streaming",                  family: "video", popular: false },
   wmv:   { ext: "wmv",   name: "WMV",   fullName: "Windows Media Video",                    mime: "video/x-ms-wmv",      description: "Microsoft Windows Media video format",                         family: "video", popular: false },
   asf:   { ext: "asf",   name: "ASF",   fullName: "Advanced Systems Format",                mime: "video/x-ms-asf",      description: "Microsoft proprietary container format",                       family: "video", popular: false },
   m2ts:  { ext: "m2ts",  name: "M2TS",  fullName: "Blu-ray MPEG Transport Stream",           mime: "video/mp2t",          description: "Blu-ray video transport stream format",                        family: "video", popular: false },
   mts:   { ext: "mts",   name: "MTS",   fullName: "AVCHD Video",                            mime: "video/mp2t",          description: "AVCHD camcorder video format",                                 family: "video", popular: false },
   ts:    { ext: "ts",    name: "TS",    fullName: "MPEG Transport Stream",                   mime: "video/mp2t",          description: "digital broadcast transport stream format",                     family: "video", popular: false },
   vob:   { ext: "vob",   name: "VOB",   fullName: "DVD Video Object",                       mime: "video/dvd",           description: "DVD-Video container format",                                   family: "video", popular: false },
   "3g2": { ext: "3g2",   name: "3G2",   fullName: "3GPP2 Multimedia",                       mime: "video/3gpp2",         description: "enhanced mobile video format",                                 family: "video", popular: false },
   swf:   { ext: "swf",   name: "SWF",   fullName: "Shockwave Flash",                        mime: "application/x-shockwave-flash", description: "Adobe Flash animation format",                               family: "video", popular: false },
   mp3:   { ext: "mp3",   name: "MP3",   fullName: "MPEG Audio Layer III",                   mime: "audio/mpeg",          description: "most compatible lossy audio format",                           family: "audio", popular: true },
   wav:   { ext: "wav",   name: "WAV",   fullName: "Waveform Audio",                         mime: "audio/wav",           description: "uncompressed high-fidelity audio format",                      family: "audio", popular: true },
   ogg:   { ext: "ogg",   name: "OGG",   fullName: "Ogg Vorbis",                             mime: "audio/ogg",           description: "free open-source audio compression format",                    family: "audio", popular: false },
   flac:  { ext: "flac",  name: "FLAC",  fullName: "Free Lossless Audio Codec",              mime: "audio/flac",          description: "lossless audio compression with high quality",                 family: "audio", popular: false },
   aac:   { ext: "aac",   name: "AAC",   fullName: "Advanced Audio Coding",                  mime: "audio/aac",           description: "modern lossy audio format with better quality than MP3",        family: "audio", popular: false },
   m4a:   { ext: "m4a",   name: "M4A",   fullName: "MPEG-4 Audio",                           mime: "audio/mp4",           description: "Apple-compatible lossy audio format",                          family: "audio", popular: false },
   opus:  { ext: "opus",  name: "Opus",  fullName: "Opus Audio",                             mime: "audio/opus",          description: "high-quality interactive audio codec",                         family: "audio", popular: false },
   wma:   { ext: "wma",   name: "WMA",   fullName: "Windows Media Audio",                    mime: "audio/x-ms-wma",      description: "Microsoft proprietary audio format",                           family: "audio", popular: false },
   aiff:  { ext: "aiff",  name: "AIFF",  fullName: "Audio Interchange File Format",           mime: "audio/x-aiff",        description: "uncompressed Apple audio format popular in professional audio", family: "audio", popular: false },
   alac:  { ext: "alac",  name: "ALAC",  fullName: "Apple Lossless Audio Codec",              mime: "audio/mp4",           description: "lossless audio codec developed by Apple",                      family: "audio", popular: false },
   amr:   { ext: "amr",   name: "AMR",   fullName: "Adaptive Multi-Rate Audio",              mime: "audio/amr",           description: "compressed audio format optimized for speech",                 family: "audio", popular: false },
   ape:   { ext: "ape",   name: "APE",   fullName: "Monkey's Audio",                          mime: "audio/x-monkeys-audio", description: "lossless audio compression format",                           family: "audio", popular: false },
   m4b:   { ext: "m4b",   name: "M4B",   fullName: "MPEG-4 Audiobook",                       mime: "audio/mp4",           description: "AAC audio format with chapter support for audiobooks",          family: "audio", popular: false },
   mid:   { ext: "mid",   name: "MIDI",  fullName: "MIDI Audio",                              mime: "audio/midi",          description: "musical instrument digital interface format",                   family: "audio", popular: false },
   mp2:   { ext: "mp2",   name: "MP2",   fullName: "MPEG-1 Audio Layer II",                   mime: "audio/mpeg",          description: "legacy audio compression format used in broadcasting",         family: "audio", popular: false },
   oga:   { ext: "oga",   name: "OGA",   fullName: "Ogg Audio",                               mime: "audio/ogg",           description: "Ogg container for Vorbis or Opus audio",                        family: "audio", popular: false },
   caf:   { ext: "caf",   name: "CAF",   fullName: "Core Audio Format",                       mime: "audio/x-caf",         description: "Apple's professional audio container format",                  family: "audio", popular: false },
   xlsx:  { ext: "xlsx",  name: "XLSX",  fullName: "Excel Spreadsheet",                         mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", description: "Microsoft Excel spreadsheet format",                             family: "data", popular: true },
   xls:   { ext: "xls",   name: "XLS",   fullName: "Excel Spreadsheet (Legacy)",                 mime: "application/vnd.ms-excel", description: "legacy Microsoft Excel format",                                family: "data", popular: false },
   epub:  { ext: "epub",  name: "EPUB",  fullName: "Electronic Publication",                  mime: "application/epub+zip", description: "open standard e-book format for reflowable content",           family: "ebook", popular: true },
  mobi:  { ext: "mobi",  name: "MOBI",  fullName: "Mobipocket E-book",                       mime: "application/x-mobipocket-ebook", description: "Amazon Kindle compatible e-book format",                      family: "ebook", popular: false },
  fb2:   { ext: "fb2",   name: "FB2",   fullName: "FictionBook E-book",                      mime: "application/x-fictionbook+xml", description: "XML-based e-book format popular for fiction",                 family: "ebook", popular: false },
  ttf:   { ext: "ttf",   name: "TTF",   fullName: "TrueType Font",                           mime: "font/ttf",             description: "industry-standard outline font format by Apple and Microsoft",  family: "font", popular: true },
  otf:   { ext: "otf",   name: "OTF",   fullName: "OpenType Font",                           mime: "font/otf",             description: "advanced font format with typographic features",                family: "font", popular: true },
  woff:  { ext: "woff",  name: "WOFF",  fullName: "Web Open Font Format",                    mime: "font/woff",            description: "compressed web font format for faster loading",                family: "font", popular: false },
  woff2: { ext: "woff2", name: "WOFF2", fullName: "Web Open Font Format 2",                  mime: "font/woff2",           description: "next-generation web font format with superior compression",     family: "font", popular: false },
  zip:   { ext: "zip",   name: "ZIP",   fullName: "ZIP Archive",                             mime: "application/zip",      description: "universal compressed archive format",                          family: "archive", popular: true },
  tar:   { ext: "tar",   name: "TAR",   fullName: "Tape Archive",                            mime: "application/x-tar",    description: "uncompressed Unix archive format",                             family: "archive", popular: false },
  gz:    { ext: "gz",    name: "GZ",    fullName: "Gzip Compressed Archive",                 mime: "application/gzip",     description: "GNU compression format commonly paired with tar",              family: "archive", popular: false },
  "7z":  { ext: "7z",    name: "7Z",    fullName: "7-Zip Archive",                           mime: "application/x-7z-compressed", description: "high-compression ratio archive format",                       family: "archive", popular: false },
  stl:   { ext: "stl",   name: "STL",   fullName: "Standard Triangle Language",               mime: "model/stl",           description: "standard format for 3D printing and CAD mesh data",            family: "3d", popular: true },
  obj:   { ext: "obj",   name: "OBJ",   fullName: "Wavefront OBJ",                            mime: "model/obj",           description: "popular 3D geometry format with optional material files",      family: "3d", popular: true },
  glb:   { ext: "glb",   name: "GLB",   fullName: "GL Transmission Format (Binary)",          mime: "model/gltf-binary",   description: "efficient binary 3D format for web and AR/VR",                  family: "3d", popular: false },
  gltf:  { ext: "gltf",  name: "glTF",  fullName: "GL Transmission Format (JSON)",            mime: "model/gltf+json",     description: "JSON-based 3D format optimized for web delivery",              family: "3d", popular: false },
} as const;

// ── Categories ───────────────────────────────────────────────────

export const CATEGORIES: ToolCategory[] = [
  { id: "image",     slug: "image",     name: "Image",     description: "Convert and optimize images between every major format",                  shortDescription: "Images",     icon: "image",     seo: { title: "Image Converter — Free Online Tool | Convertmyfiles", description: "Free online image converter. Convert PNG, JPG, WebP, SVG, GIF and more. Private browser-based conversion." } },
  { id: "document",  slug: "document",  name: "Document",  description: "Convert documents and work with PDF files",                                shortDescription: "Documents",  icon: "file-text", seo: { title: "Document Converter — Free Online Tool | Convertmyfiles", description: "Free online document converter. Convert PDF, DOCX, TXT and more. No upload, 100% private." } },
  { id: "video",     slug: "video",     name: "Video",     description: "Convert video files between formats",                                      shortDescription: "Videos",     icon: "video",     seo: { title: "Video Converter — Free Online Tool | Convertmyfiles", description: "Free online video converter. Convert MP4, WebM, AVI and more. Browser-based with no file size limits." } },
  { id: "audio",     slug: "audio",     name: "Audio",     description: "Convert audio files between formats",                                      shortDescription: "Audio",     icon: "music",     seo: { title: "Audio Converter — Free Online Tool | Convertmyfiles", description: "Free online audio converter. Convert MP3, WAV, FLAC, OGG and more. High quality, private." } },
  { id: "other",     slug: "other",     name: "Other",     description: "Additional utilities for developers, text, and data",                      shortDescription: "Other",     icon: "wrench",    seo: { title: "Online Converter Tools — Free Utilities | Convertmyfiles", description: "Browse all free online converter tools. Privacy-first, browser-based file conversion." } },
];

const CATEGORY_MAP = new Map(CATEGORIES.map(c => [c.id, c]));

export const CATEGORY_URLS: Record<string, string> = {
  image: "image-tools",
  document: "pdf-tools",
  video: "video-tools",
  audio: "audio-tools",
  other: "developer-tools",
};

export const URL_TO_CATEGORY: Record<string, string> = {
  "image-tools": "image",
  "pdf-tools": "document",
  "video-tools": "video",
  "audio-tools": "audio",
  "developer-tools": "other",
};

// ── Format Pair Generators (10k+ scale) ──────────────────────────

export const FORMAT_GROUPS: Record<string, string[]> = {
  image:    ["png", "jpg", "jpeg", "webp", "gif", "bmp", "svg", "ico", "avif", "tiff", "heic"],
  document: ["pdf", "doc", "docx", "txt", "html", "md", "rtf", "csv", "json", "xml", "xlsx", "xls"],
  video:    ["mp4", "webm", "avi", "mov", "mkv", "m4v", "mpeg", "ogv", "3gp", "flv", "wmv", "asf", "m2ts", "mts", "ts", "vob", "3g2", "swf"],
  audio:    ["mp3", "wav", "ogg", "flac", "aac", "m4a", "opus", "wma", "aiff", "alac", "amr", "ape", "m4b", "mid", "mp2", "oga", "caf"],
  ebook:    ["epub", "mobi", "fb2"],
  font:     ["ttf", "otf", "woff", "woff2"],
  archive:  ["zip", "tar", "gz", "7z"],
  "3d":     ["stl", "obj", "glb", "gltf"],
};

function generateGeneratedEntries(): RegistryEntry[] {
  const result: RegistryEntry[] = [];
  // Only ebook and 3D tools are still coming soon — all other categories are active.
  const comingSoonCategories = new Set(["ebook", "3d"]);
  // Map format groups to their actual engine — images use "image", docs use "document", etc.
  const categoryEngineMap: Record<string, Engine> = {
    image: "image", document: "document", video: "video", audio: "audio",
    ebook: "image", font: "image", archive: "archive", "3d": "image",
  };
  for (const [category, exts] of Object.entries(FORMAT_GROUPS)) {
    for (const input of exts) {
      for (const output of exts) {
        if (input === output) continue;
        const fi = FORMATS[input];
        const fo = FORMATS[output];
        const bothPopular = (fi?.popular ?? false) && (fo?.popular ?? false);
        result.push({
          slug: `${input}-to-${output}`,
          name: `${(fi?.name || input.toUpperCase())} to ${(fo?.name || output.toUpperCase())}`,
          category,
          inputFormats: [input],
          outputFormats: [output],
          engine: categoryEngineMap[category] || (category as Engine),
          popular: bothPopular,
          comingSoon: comingSoonCategories.has(category),
          autoGenerated: true,
        });
      }
    }
  }
  return result;
}

// ── THE REGISTRY: Single source of truth ─────────────────────────
// ★ Add one entry here to create a new tool with full auto-generation

const registryEntries: RegistryEntry[] = [
  // ── Image Tools ──
  { slug: "png-to-jpg",   name: "PNG to JPG",   category: "image",     inputFormats: ["png"],           outputFormats: ["jpg", "jpeg"], engine: "image", popular: true },
  { slug: "jpg-to-png",   name: "JPG to PNG",   category: "image",     inputFormats: ["jpg", "jpeg"],   outputFormats: ["png"],         engine: "image", popular: true },
  { slug: "webp-to-png",  name: "WebP to PNG",  category: "image",     inputFormats: ["webp"],          outputFormats: ["png"],         engine: "image", popular: true },
  { slug: "png-to-webp",  name: "PNG to WebP",  category: "image",     inputFormats: ["png"],           outputFormats: ["webp"],        engine: "image", popular: true },
  { slug: "jpg-to-webp",  name: "JPG to WebP",  category: "image",     inputFormats: ["jpg", "jpeg"],   outputFormats: ["webp"],        engine: "image", popular: false },
  { slug: "svg-to-png",   name: "SVG to PNG",   category: "image",     inputFormats: ["svg"],           outputFormats: ["png"],         engine: "image", popular: true },
  { slug: "gif-to-png",   name: "GIF to PNG",   category: "image",     inputFormats: ["gif"],           outputFormats: ["png"],         engine: "image", popular: false },
  { slug: "bmp-to-png",   name: "BMP to PNG",   category: "image",     inputFormats: ["bmp"],           outputFormats: ["png"],         engine: "image", popular: false },
  { slug: "webp-to-jpg",  name: "WebP to JPG",  category: "image",     inputFormats: ["webp"],          outputFormats: ["jpg", "jpeg"], engine: "image", popular: false },
  { slug: "png-to-gif",   name: "PNG to GIF",   category: "image",     inputFormats: ["png"],           outputFormats: ["gif"],         engine: "image", popular: false },
  { slug: "jpg-to-gif",   name: "JPG to GIF",   category: "image",     inputFormats: ["jpg", "jpeg"],   outputFormats: ["gif"],         engine: "image", popular: false },
  { slug: "png-to-ico",   name: "PNG to ICO",   category: "image",     inputFormats: ["png"],           outputFormats: ["ico"],         engine: "image", popular: false },
  { slug: "svg-to-jpg",   name: "SVG to JPG",   category: "image",     inputFormats: ["svg"],           outputFormats: ["jpg", "jpeg"], engine: "image", popular: false },
  { slug: "avif-to-png",  name: "AVIF to PNG",  category: "image",     inputFormats: ["avif"],          outputFormats: ["png"],         engine: "image", popular: false },
  { slug: "tiff-to-png",  name: "TIFF to PNG",  category: "image",     inputFormats: ["tiff"],          outputFormats: ["png"],         engine: "image", popular: false },
  { slug: "svg-to-webp",  name: "SVG to WebP",  category: "image",     inputFormats: ["svg"],           outputFormats: ["webp"],        engine: "image", popular: false },
  { slug: "gif-to-webp",  name: "GIF to WebP",  category: "image",     inputFormats: ["gif"],           outputFormats: ["webp"],        engine: "image", popular: false },
  { slug: "png-to-avif",  name: "PNG to AVIF",  category: "image",     inputFormats: ["png"],           outputFormats: ["avif"],        engine: "image", popular: false },
  { slug: "jpg-to-avif",  name: "JPG to AVIF",  category: "image",     inputFormats: ["jpg", "jpeg"],   outputFormats: ["avif"],        engine: "image", popular: false },
  { slug: "webp-to-gif",  name: "WebP to GIF",  category: "image",     inputFormats: ["webp"],          outputFormats: ["gif"],         engine: "image", popular: false },
  { slug: "ico-to-png",   name: "ICO to PNG",   category: "image",     inputFormats: ["ico"],           outputFormats: ["png"],         engine: "image", popular: false },
  { slug: "avif-to-jpg",  name: "AVIF to JPG",  category: "image",     inputFormats: ["avif"],          outputFormats: ["jpg", "jpeg"], engine: "image", popular: false },
  { slug: "tiff-to-jpg",  name: "TIFF to JPG",  category: "image",     inputFormats: ["tiff"],          outputFormats: ["jpg", "jpeg"], engine: "image", popular: false },
  { slug: "heic-to-jpg",  name: "HEIC to JPG",  category: "image",     inputFormats: ["heic"],          outputFormats: ["jpg", "jpeg", "png"], engine: "image", popular: true },

  // ── Image Operations ──
  { slug: "compress-image", name: "Compress Image", category: "image", inputFormats: ["jpg", "jpeg", "png", "webp"], outputFormats: ["jpg", "jpeg", "png", "webp"], engine: "image", popular: true },
  { slug: "crop-image",     name: "Crop Image",     category: "image", inputFormats: ["jpg", "jpeg", "png", "webp"], outputFormats: ["jpg", "jpeg", "png", "webp"], engine: "image", popular: false },
  { slug: "rotate-image",   name: "Rotate Image",   category: "image", inputFormats: ["jpg", "jpeg", "png", "webp"], outputFormats: ["jpg", "jpeg", "png", "webp"], engine: "image", popular: false },
  { slug: "flip-image",     name: "Flip Image",     category: "image", inputFormats: ["jpg", "jpeg", "png", "webp"], outputFormats: ["jpg", "jpeg", "png", "webp"], engine: "image", popular: false },
  { slug: "resize-image",   name: "Resize Image",   category: "image", inputFormats: ["jpg", "jpeg", "png", "webp"], outputFormats: ["jpg", "jpeg", "png", "webp"], engine: "image", popular: false },
  { slug: "image-to-ico",   name: "Image to ICO",   category: "image", inputFormats: ["png", "jpg", "jpeg"],       outputFormats: ["ico"],         engine: "image", popular: false },

  // ── Document Tools ──
  { slug: "image-to-pdf", name: "Image to PDF", category: "document",  inputFormats: ["png", "jpg", "jpeg", "webp", "gif", "bmp"], outputFormats: ["pdf"], engine: "document", popular: true },
  { slug: "jpg-to-pdf",   name: "JPG to PDF",   category: "document",  inputFormats: ["jpg", "jpeg"],   outputFormats: ["pdf"],         engine: "document", popular: false },
  { slug: "png-to-pdf",   name: "PNG to PDF",   category: "document",  inputFormats: ["png"],           outputFormats: ["pdf"],         engine: "document", popular: false },
  { slug: "txt-to-pdf",   name: "TXT to PDF",   category: "document",  inputFormats: ["txt"],           outputFormats: ["pdf"],         engine: "document", popular: false },
  { slug: "pdf-to-jpg",   name: "PDF to JPG",   category: "document",  inputFormats: ["pdf"],           outputFormats: ["jpg", "jpeg"], engine: "document", popular: false },
  { slug: "pdf-to-png",   name: "PDF to PNG",   category: "document",  inputFormats: ["pdf"],           outputFormats: ["png"],         engine: "document", popular: true },

  // ── PDF Operations ──
  { slug: "merge-pdf",    name: "Merge PDF",    category: "document",  inputFormats: ["pdf"],           outputFormats: ["pdf"],         engine: "document", popular: true },
  { slug: "split-pdf",    name: "Split PDF",    category: "document",  inputFormats: ["pdf"],           outputFormats: ["pdf"],         engine: "document", popular: false },
  { slug: "compress-pdf", name: "Compress PDF",  category: "document",  inputFormats: ["pdf"],           outputFormats: ["pdf"],         engine: "document", popular: false },
  { slug: "rotate-pdf",   name: "Rotate PDF",   category: "document",  inputFormats: ["pdf"],           outputFormats: ["pdf"],         engine: "document", popular: false },
  { slug: "delete-pdf-pages",  name: "Delete PDF Pages",  category: "document", inputFormats: ["pdf"], outputFormats: ["pdf"], engine: "document", popular: false },
  { slug: "extract-pdf-pages", name: "Extract PDF Pages", category: "document", inputFormats: ["pdf"], outputFormats: ["pdf"], engine: "document", popular: false },
  { slug: "add-page-numbers",  name: "Add Page Numbers",  category: "document", inputFormats: ["pdf"], outputFormats: ["pdf"], engine: "document", popular: false },

  // ── Data Tools ──
  { slug: "json-to-csv",  name: "JSON to CSV",  category: "other",     inputFormats: ["json"],          outputFormats: ["csv"],         engine: "data", popular: true },
  { slug: "csv-to-json",  name: "CSV to JSON",  category: "other",     inputFormats: ["csv"],           outputFormats: ["json"],        engine: "data", popular: true },
  { slug: "json-to-xml",  name: "JSON to XML",  category: "other",     inputFormats: ["json"],          outputFormats: ["xml"],         engine: "data", popular: false },
  { slug: "xml-to-json",  name: "XML to JSON",  category: "other",     inputFormats: ["xml"],           outputFormats: ["json"],        engine: "data", popular: false },
  { slug: "csv-to-xml",   name: "CSV to XML",   category: "other",     inputFormats: ["csv"],           outputFormats: ["xml"],         engine: "data", popular: false },
  { slug: "xml-to-csv",   name: "XML to CSV",   category: "other",     inputFormats: ["xml"],           outputFormats: ["csv"],         engine: "data", popular: false },

  // ── Markup / Text ──
  { slug: "html-to-md",   name: "HTML to Markdown",  category: "other", inputFormats: ["html"],         outputFormats: ["md"],          engine: "text", popular: false },
  { slug: "md-to-html",   name: "Markdown to HTML",  category: "other", inputFormats: ["md"],           outputFormats: ["html"],        engine: "text", popular: true },
  { slug: "html-to-txt",  name: "HTML to Text",      category: "other", inputFormats: ["html"],         outputFormats: ["txt"],         engine: "text", popular: false },
  { slug: "txt-to-html",  name: "Text to HTML",      category: "other", inputFormats: ["txt"],          outputFormats: ["html"],        engine: "text", popular: false },
  { slug: "json-format",  name: "JSON Formatter",    category: "other", inputFormats: ["json"],         outputFormats: ["json"],        engine: "text", popular: true },
  { slug: "html-format",  name: "HTML Formatter",    category: "other", inputFormats: ["html"],         outputFormats: ["html"],        engine: "text", popular: false },
  { slug: "css-format",   name: "CSS Formatter",     category: "other", inputFormats: ["txt"],          outputFormats: ["txt"],         engine: "text", popular: false },
  { slug: "json-minify",  name: "JSON Minifier",     category: "other", inputFormats: ["json"],         outputFormats: ["json"],        engine: "text", popular: false },

  // ── Developer Utilities ──
  { slug: "json-validate",   name: "JSON Validator",   category: "other", inputFormats: ["json"], outputFormats: ["txt"], engine: "text", popular: false },
  { slug: "json-to-yaml",    name: "JSON to YAML",     category: "other", inputFormats: ["json"], outputFormats: ["txt"], engine: "text", popular: false },
  { slug: "yaml-to-json",    name: "YAML to JSON",     category: "other", inputFormats: ["txt"],  outputFormats: ["json"], engine: "text", popular: false },
  { slug: "base64-encode",   name: "Base64 Encode",    category: "other", inputFormats: ["txt"],  outputFormats: ["txt"], engine: "text", popular: false },
  { slug: "base64-decode",   name: "Base64 Decode",    category: "other", inputFormats: ["txt"],  outputFormats: ["txt"], engine: "text", popular: false },
  { slug: "url-encode",      name: "URL Encode",       category: "other", inputFormats: ["txt"],  outputFormats: ["txt"], engine: "text", popular: false },
  { slug: "url-decode",      name: "URL Decode",       category: "other", inputFormats: ["txt"],  outputFormats: ["txt"], engine: "text", popular: false },
  { slug: "hash-generator",  name: "Hash Generator",   category: "other", inputFormats: ["txt"],  outputFormats: ["txt"], engine: "text", popular: false },

  // ── Text Utilities ──
  { slug: "text-to-uppercase", name: "Text to Uppercase",   category: "other", inputFormats: ["txt"], outputFormats: ["txt"], engine: "text", popular: false },
  { slug: "text-to-lowercase", name: "Text to Lowercase",   category: "other", inputFormats: ["txt"], outputFormats: ["txt"], engine: "text", popular: false },
  { slug: "text-to-titlecase", name: "Text to Title Case",  category: "other", inputFormats: ["txt"], outputFormats: ["txt"], engine: "text", popular: false },
  { slug: "word-counter",      name: "Word Counter",        category: "other", inputFormats: ["txt"], outputFormats: ["txt"], engine: "text", popular: false },
  { slug: "text-reverser",     name: "Text Reverser",       category: "other", inputFormats: ["txt"], outputFormats: ["txt"], engine: "text", popular: false },
  { slug: "uuid-generator",    name: "UUID Generator",      category: "other", inputFormats: ["txt"], outputFormats: ["txt"], engine: "text", popular: false },
  { slug: "css-minifier",      name: "CSS Minifier",        category: "other", inputFormats: ["txt"], outputFormats: ["txt"], engine: "text", popular: false },

  // ── Markdown Tools ──
  { slug: "md-to-txt",  name: "Markdown to Text", category: "other", inputFormats: ["md"],  outputFormats: ["txt"], engine: "text", popular: false },
  { slug: "txt-to-md",  name: "Text to Markdown", category: "other", inputFormats: ["txt"], outputFormats: ["md"],  engine: "text", popular: false },

  // ── Additional Video Format Pairs ──
  { slug: "webm-to-avi", name: "WebM to AVI", category: "video", inputFormats: ["webm"], outputFormats: ["avi"], engine: "video", popular: false },
  { slug: "mov-to-webm", name: "MOV to WebM", category: "video", inputFormats: ["mov"],  outputFormats: ["webm"], engine: "video", popular: false },
  { slug: "mkv-to-mp4",  name: "MKV to MP4",  category: "video", inputFormats: ["mkv"],  outputFormats: ["mp4"],  engine: "video", popular: false },
  { slug: "mp4-to-mkv",  name: "MP4 to MKV",  category: "video", inputFormats: ["mp4"],  outputFormats: ["mkv"],  engine: "video", popular: false },
  { slug: "webm-to-mov", name: "WebM to MOV", category: "video", inputFormats: ["webm"], outputFormats: ["mov"],  engine: "video", popular: false },
  { slug: "avi-to-webm", name: "AVI to WebM", category: "video", inputFormats: ["avi"],  outputFormats: ["webm"], engine: "video", popular: false },

  // ── Additional Audio Format Pairs ──
  { slug: "aac-to-mp3",  name: "AAC to MP3",  category: "audio", inputFormats: ["aac"],  outputFormats: ["mp3"],  engine: "audio", popular: false },
  { slug: "mp3-to-ogg",  name: "MP3 to OGG",  category: "audio", inputFormats: ["mp3"],  outputFormats: ["ogg"],  engine: "audio", popular: false },
  { slug: "flac-to-wav", name: "FLAC to WAV", category: "audio", inputFormats: ["flac"], outputFormats: ["wav"],  engine: "audio", popular: false },
  { slug: "wav-to-aac",  name: "WAV to AAC",  category: "audio", inputFormats: ["wav"],  outputFormats: ["aac"],  engine: "audio", popular: false },

  // ── Video Tools ──
  { slug: "mp4-to-webm",  name: "MP4 to WebM",  category: "video",     inputFormats: ["mp4"],           outputFormats: ["webm"],        engine: "video", popular: true },
  { slug: "webm-to-mp4",  name: "WebM to MP4",  category: "video",     inputFormats: ["webm"],          outputFormats: ["mp4"],         engine: "video", popular: true },
  { slug: "mp4-to-avi",   name: "MP4 to AVI",   category: "video",     inputFormats: ["mp4"],           outputFormats: ["avi"],         engine: "video", popular: false },
  { slug: "mov-to-mp4",   name: "MOV to MP4",   category: "video",     inputFormats: ["mov"],           outputFormats: ["mp4"],         engine: "video", popular: true },
  { slug: "avi-to-mp4",   name: "AVI to MP4",   category: "video",     inputFormats: ["avi"],           outputFormats: ["mp4"],         engine: "video", popular: false },
  { slug: "mp4-to-mov",   name: "MP4 to MOV",   category: "video",     inputFormats: ["mp4"],           outputFormats: ["mov"],         engine: "video", popular: false },
  { slug: "mp4-to-gif",   name: "MP4 to GIF",   category: "video",     inputFormats: ["mp4"],           outputFormats: ["gif"],         engine: "video", popular: true },
  { slug: "video-to-gif", name: "Video to GIF", category: "video",     inputFormats: ["mp4", "webm", "mov", "avi"], outputFormats: ["gif"], engine: "video", popular: true },
  { slug: "compress-video", name: "Compress Video", category: "video", inputFormats: ["mp4", "webm", "mov"], outputFormats: ["mp4"], engine: "video", popular: false },
  { slug: "resize-video", name: "Resize Video", category: "video", inputFormats: ["mp4", "webm", "mov"], outputFormats: ["mp4"], engine: "video", popular: false },

  // ── Audio Extraction ──
  { slug: "mp4-to-mp3",   name: "MP4 to MP3",   category: "audio",     inputFormats: ["mp4"],           outputFormats: ["mp3"],         engine: "audio", popular: true },

  // ── Audio Tools ──
  { slug: "mp3-to-wav",   name: "MP3 to WAV",   category: "audio",     inputFormats: ["mp3"],           outputFormats: ["wav"],         engine: "audio", popular: true },
  { slug: "wav-to-mp3",   name: "WAV to MP3",   category: "audio",     inputFormats: ["wav"],           outputFormats: ["mp3"],         engine: "audio", popular: true },
  { slug: "mp3-to-flac",  name: "MP3 to FLAC",  category: "audio",     inputFormats: ["mp3"],           outputFormats: ["flac"],        engine: "audio", popular: false },
  { slug: "flac-to-mp3",  name: "FLAC to MP3",  category: "audio",     inputFormats: ["flac"],          outputFormats: ["mp3"],         engine: "audio", popular: false },
  { slug: "wav-to-flac",  name: "WAV to FLAC",  category: "audio",     inputFormats: ["wav"],           outputFormats: ["flac"],        engine: "audio", popular: false },
  { slug: "ogg-to-mp3",   name: "OGG to MP3",   category: "audio",     inputFormats: ["ogg"],           outputFormats: ["mp3"],         engine: "audio", popular: false },
  { slug: "wav-to-ogg",   name: "WAV to OGG",   category: "audio",     inputFormats: ["wav"],           outputFormats: ["ogg"],         engine: "audio", popular: false },
  { slug: "mp3-to-aac",   name: "MP3 to AAC",   category: "audio",     inputFormats: ["mp3"],           outputFormats: ["aac"],         engine: "audio", popular: false },

  // ── Office / Document Conversions ──
  { slug: "docx-to-pdf",  name: "DOCX to PDF",  category: "document",  inputFormats: ["docx"],          outputFormats: ["pdf"],         engine: "document", popular: true },
  { slug: "pdf-to-docx",  name: "PDF to DOCX",  category: "document",  inputFormats: ["pdf"],           outputFormats: ["docx"],        engine: "document", popular: true },
  { slug: "xlsx-to-pdf",  name: "XLSX to PDF",  category: "document",  inputFormats: ["xlsx"],          outputFormats: ["pdf"],         engine: "document", popular: true },
  { slug: "pdf-to-xlsx",  name: "PDF to XLSX",  category: "document",  inputFormats: ["pdf"],           outputFormats: ["xlsx"],        engine: "document", popular: true },
  { slug: "csv-to-xlsx",  name: "CSV to XLSX",  category: "document",  inputFormats: ["csv"],           outputFormats: ["xlsx"],        engine: "document", popular: false },
  { slug: "json-to-xlsx", name: "JSON to XLSX", category: "document",  inputFormats: ["json"],          outputFormats: ["xlsx"],        engine: "document", popular: false },
  { slug: "txt-to-xlsx",  name: "TXT to XLSX",  category: "document",  inputFormats: ["txt"],           outputFormats: ["xlsx"],        engine: "document", popular: false },

  // ── Archive Tools ──
  { slug: "create-archive",   name: "Create ZIP Archive",   category: "other", inputFormats: ["zip"],  outputFormats: ["zip"],  engine: "archive", popular: true },
  { slug: "extract-archive",  name: "Extract ZIP Archive",  category: "other", inputFormats: ["zip"],  outputFormats: ["zip"],  engine: "archive", popular: false },

  // ── Ebook Tools ──
  { slug: "epub-to-pdf", name: "EPUB to PDF", category: "document", inputFormats: ["epub"], outputFormats: ["pdf"], engine: "document", popular: true },

  // ── OCR Tools ──
  { slug: "image-to-text", name: "Image to Text (OCR)", category: "other", inputFormats: ["png", "jpg", "jpeg", "webp"], outputFormats: ["txt"], engine: "text", popular: true },
];

// ── Auto-Generation Helpers ─────────────────────────────────────

function fmt(ext: string): FormatDefinition {
  return FORMATS[ext] || { ext, name: ext.toUpperCase(), fullName: ext.toUpperCase(), mime: "application/octet-stream", description: `${ext.toUpperCase()} format`, family: "other", popular: false };
}

function engineToProcessingType(engine: Engine): ProcessingType {
  if (engine === "text" || engine === "data") return "other";
  if (engine === "archive") return "other";
  return engine;
}

function generateDescription(input: RegistryEntry): string {
  const i = fmt(input.inputFormats[0]);
  const o = fmt(input.outputFormats[0]);
  if (i.ext === o.ext) {
    return `${input.name} — online for free. Format, validate, and transform your ${i.fullName} files. 100% browser-based, no upload required, completely private.`;
  }
  return `Convert ${i.name} to ${o.name} online for free. ${i.fullName} (${i.description}) to ${o.fullName} (${o.description}). 100% browser-based, no upload required, completely private.`;
}

function generateLongDescription(input: RegistryEntry): string {
  const i = fmt(input.inputFormats[0]);
  const o = fmt(input.outputFormats[0]);
  if (i.ext === o.ext) {
    return `Use our free online ${input.name.toLowerCase()} tool to beautify and clean up your ${i.name} files.\n\nAll processing happens directly in your browser using client-side technologies — your files never leave your device. Simply upload your ${i.name} file and download the formatted result instantly.`;
  }
  return `Use our free online converter to transform ${i.name} (${i.ext.toUpperCase()}) files into ${o.name} (${o.ext.toUpperCase()}) format.\n\n${i.fullName} is a ${i.description.toLowerCase()}. ${o.fullName} is a ${o.description.toLowerCase()}.\n\nAll processing happens directly in your browser using client-side technologies — your files never leave your device. Simply upload your ${i.name} file, choose ${o.name} as the output format, and download your converted file instantly.`;
}

function pickTemplate<T>(items: T[], seed: string): T {
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    const char = seed.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash;
  }
  return items[Math.abs(hash) % items.length];
}

function generateSeo(input: RegistryEntry, override?: Partial<ToolSeo>): ToolSeo {
  if (override?.title && override?.description) {
    return { title: override.title, description: override.description, keywords: override.keywords || [] };
  }

  const i = fmt(input.inputFormats[0]);
  const o = fmt(input.outputFormats[0]);
  const name = input.name;
  const isSame = i.ext === o.ext;
  const inputExt = i.ext.toUpperCase();
  const outputExt = o.ext.toUpperCase();
  const isUtility = input.slug.includes("format") || input.slug.includes("minify") || input.slug.includes("validate") ||
    input.slug.includes("encode") || input.slug.includes("decode") || input.slug.includes("hash") ||
    input.slug.includes("generator") || input.slug.includes("counter") || input.slug.includes("reverser");

  const keywords = isSame
    ? [
        `${i.ext} ${input.slug.includes("minify") ? "minifier" : "formatter"}`,
        `free ${i.ext} ${input.slug.includes("minify") ? "minifier" : "formatter"}`,
        `online ${i.ext} ${input.slug.includes("minify") ? "minify" : "format"}`,
        `${i.name} ${input.slug.includes("minify") ? "minifier" : "formatter"}`,
        `${input.slug.includes("minify") ? "minify" : "beautify"} ${i.ext}`,
        `online ${i.ext} tool`,
      ]
    : [
        `convert ${i.ext} to ${o.ext}`,
        `${i.ext} to ${o.ext} converter`,
        `free ${i.ext} to ${o.ext}`,
        `${i.name} to ${o.name}`,
        `online ${i.ext} converter`,
        `${i.name} converter`,
        `free online ${i.ext} to ${o.ext}`,
      ];

  // Unique title templates based on tool type
  const titleTemplates = isSame
    ? [
        `Free ${name} Online | Convertmyfiles`,
        `${name} — Online ${isUtility ? "Utility" : "Tool"} | Convertmyfiles`,
      ]
    : [
        `Free ${name} Online | Convertmyfiles`,
        `${name} — Free Online Converter | Convertmyfiles`,
        `${i.name} to ${o.name} | Free Online File Converter`,
      ];

  const title = pickTemplate(titleTemplates, input.slug + "-title");

  // Unique description templates
  const descriptionTemplates = isSame
    ? [
        `${name} online for free. ${input.slug.includes("minify") ? "Minify" : "Format and beautify"} your ${i.name} (${inputExt}) files in your browser. 100% private, no upload, no servers, no tracking. Instant results.`,
        `${name} — a free online tool to ${input.slug.includes("minify") ? "minify" : "format"} ${i.name} files. Browser-based processing ensures your ${inputExt} data stays private on your device.`,
      ]
    : [
        `Convert ${i.name} (${inputExt}) to ${o.name} (${outputExt}) online for free. 100% browser-based conversion with privacy first — no upload, no servers, no tracking. ${name} in seconds.`,
        `Free online ${name} converter. Transform your ${i.name} files into ${o.name} format instantly in your browser. Private, secure, and requires no signup.`,
      ];

  const description = pickTemplate(descriptionTemplates, input.slug + "-desc");

  return { title, description, keywords };
}

function generateShortName(input: RegistryEntry): string {
  if (input.inputFormats[0] === input.outputFormats[0]) return input.name;
  return `${input.inputFormats[0].toUpperCase()} → ${input.outputFormats[0].toUpperCase()}`;
}

function generateTitle(input: RegistryEntry): string {
  if (input.slug.includes("format") || input.slug.includes("minify")) return input.name;
  return `${input.name} Converter`;
}

function generateFaq(input: RegistryEntry, override?: ToolFaqEntry[]): ToolFaqEntry[] {
  if (override && override.length > 0) return override;

  const i = fmt(input.inputFormats[0]);
  const o = fmt(input.outputFormats[0]);
  const inputName = i.name;
  const outputName = o.name;
  const inputExt = i.ext.toUpperCase();
  const outputExt = o.ext.toUpperCase();
  const inputFull = i.fullName;
  const outputFull = o.fullName;
  const isSame = i.ext === o.ext;
  const isUtility = input.slug.includes("format") || input.slug.includes("minify") || input.slug.includes("validate") ||
    input.slug.includes("encode") || input.slug.includes("decode") || input.slug.includes("hash") ||
    input.slug.includes("generator") || input.slug.includes("counter") || input.slug.includes("reverser");
  const isOperation = input.slug.includes("compress") || input.slug.includes("crop") || input.slug.includes("rotate") ||
    input.slug.includes("flip") || input.slug.includes("resize") || input.slug.includes("merge") ||
    input.slug.includes("split") || input.slug.includes("delete") || input.slug.includes("extract");

  if (isSame) {
    const verb = input.slug.includes("minify") ? "minify" : input.slug.includes("validate") ? "validate" : input.slug.includes("encode") ? "encode" : "format";
    const noun = input.slug.includes("minify") ? "minifier" : input.slug.includes("validate") ? "validator" : input.slug.includes("encode") ? "encoder" : input.slug.includes("decode") ? "decoder" : "formatter";
    return [
      { q: `Is it free to ${verb} ${inputExt} files?`, a: `Yes, absolutely. Our ${inputName} ${noun} is completely free with no hidden fees, no premium tiers, and no credit card required. You can use it as many times as you need.` },
      { q: `What does ${inputExt} ${verb} mean?`, a: `${verb.charAt(0).toUpperCase() + verb.slice(1)}ing ${inputExt} means ${verb === "format" ? `restructuring the ${inputName} content to follow proper indentation and syntax conventions, making it easier to read and maintain` : verb === "minify" ? `removing unnecessary characters like whitespace, comments, and line breaks from ${inputName} to reduce file size` : verb === "validate" ? `checking your ${inputName} content against the format specification to ensure it is syntactically correct and properly structured` : verb === "encode" ? `converting your data into a ${inputName} encoded string representation, useful for transmitting data in text-based protocols` : `converting a ${inputName} encoded string back to its original binary or text representation`}. This tool does all of this locally in your browser.` },
      { q: `Are my ${inputExt} files secure?`, a: `Complete security. Your files never leave your device. All processing happens locally in your browser using client-side JavaScript. No data is transmitted, stored, or logged anywhere.` },
      { q: `What is the maximum file size I can process?`, a: `There is no hard cap. Since everything runs locally, the limit depends on your device's available memory. For most modern devices, files up to 100MB work smoothly.` },
      { q: `Do I need to install anything?`, a: `No installation needed. Everything runs in your web browser. No extensions, plugins, or software downloads required. Just open the page and start working.` },
    ];
  }

  if (isOperation) {
    const opName = input.name.toLowerCase();
    return [
      { q: `What does the ${opName} tool do?`, a: `The ${inputName} ${opName} tool lets you ${opName} your ${inputName} files directly in your browser. It processes images locally using the Canvas API, giving you full control over the operation while keeping your files private.` },
      { q: `Will ${opName} reduce the quality of my ${inputExt} files?`, a: `No, the operation preserves original quality. For JPEG and WebP outputs, you can control the quality level from the settings panel. By default, we use a high-quality setting that balances file size and visual fidelity.` },
      { q: `Can I undo the ${opName} operation?`, a: `The operation creates a new processed file while keeping your original file untouched on your device. If you are not satisfied with the result, simply convert again with different settings.` },
      { q: `Are my ${inputExt} files safe?`, a: `Yes. All processing happens locally in your browser. Your original files are never uploaded anywhere. Once you close the page, all processed data is permanently deleted.` },
      { q: `Do I need any design skills to use this tool?`, a: `Not at all. The tool is designed to be simple and intuitive. Just upload your file, adjust the settings if needed, and download the result. The interface guides you through each step.` },
    ];
  }

  // Format conversion FAQ with format-specific details
  return [
    { q: `Is it free to convert ${inputExt} to ${outputExt}?`, a: `Yes, absolutely. Our ${inputName} to ${outputName} converter is completely free with no hidden fees, no premium tiers, and no credit card required. You can convert as many files as you want, whenever you need.` },
    { q: `Why would I need to convert ${inputExt} to ${outputExt}?`, a: `${inputFull} and ${outputFull} serve different purposes. ${inputName} is ${i.description.toLowerCase()}, while ${outputName} is ${o.description.toLowerCase()}. Converting between them is necessary when your workflow requires compatibility with specific software, platforms, or devices that prefer one format over the other.` },
    { q: `Will the conversion lose quality?`, a: `Our conversion engine preserves the highest possible quality. ${inputName} uses ${i.description} and ${outputName} uses ${o.description}. We apply optimal conversion parameters to maintain fidelity while ensuring compatibility with the target format.` },
    { q: `How fast is the ${inputExt} to ${outputExt} conversion?`, a: `Conversion is nearly instantaneous. Since your file never leaves your device, there is no upload or download latency. Most files process in under a second. Larger files may take slightly longer depending on your device's processing power.` },
    { q: `Are my ${inputExt} files private?`, a: `Absolutely. Unlike cloud-based converters that upload files to remote servers, all processing happens locally in your browser using client-side technology. Your ${inputName} files never leave your device. Once you close the page, everything is permanently deleted.` },
    { q: `What is the maximum file size I can convert?`, a: `There is no fixed limit. Because files stay on your device, the only constraint is your browser's memory capacity. For most modern devices, this comfortably handles files up to 100MB or more.` },
    { q: `Can I convert multiple ${inputExt} files at once?`, a: `Yes, depending on the tool. Our converter supports batch conversion for multiple files. Each file is processed individually, and you can download them one by one or all at once.` },
    { q: `Does the ${inputExt} to ${outputExt} converter work on mobile?`, a: `Yes, fully. Our converter works on any device with a modern web browser — iPhone, Android, tablet, or desktop. The interface adapts to your screen size and supports touch input.` },
  ];
}

function computeRelatedSlugs(slug: string, categoryId: string, inputFormats: string[], outputFormats: string[]): string[] {
  // In production, this would query a graph. For build-time, compute from all loaded tools.
  // This is populated after the full tool list is built.
  return [];
}

// ── Build Pipeline ──────────────────────────────────────────────

const generatedEntries = generateGeneratedEntries();
const existingSlugs = new Set(registryEntries.map((e) => e.slug));
const filteredGenerated = generatedEntries.filter((e) => !existingSlugs.has(e.slug));
const allEntries = [...registryEntries, ...filteredGenerated];

/** Build a ToolDefinition from a RegistryEntry */
function buildEntry(entry: RegistryEntry): ToolDefinition {
  const i = fmt(entry.inputFormats[0]);
  const o = fmt(entry.outputFormats[0]);
  const seo = generateSeo(entry, entry.seo);
  const faq = generateFaq(entry, entry.faq);
  const content = generateToolContent({
    slug: entry.slug,
    name: entry.name,
    inputFormat: i,
    outputFormat: entry.outputFormats.length > 0 ? o : null,
    inputFormats: entry.inputFormats,
    outputFormats: entry.outputFormats,
    categoryId: entry.category,
    engine: entry.engine,
  });
  return {
    id: entry.slug,
    slug: entry.slug,
    name: entry.name,
    shortName: generateShortName(entry),
    title: generateTitle(entry),
    description: seo.description,
    longDescription: content.introduction,
    categoryId: entry.category,
    inputFormat: i,
    outputFormat: entry.outputFormats.length > 0 ? o : null,
    inputFormats: entry.inputFormats,
    outputFormats: entry.outputFormats,
    engine: entry.engine,
    processingType: engineToProcessingType(entry.engine),
    popular: entry.popular ?? false,
    comingSoon: entry.comingSoon ?? false,
    seo,
    faq,
    relatedSlugs: [],
    content,
  };
}

function computeSimilarity(a: ToolDefinition, b: ToolDefinition): number {
  let score = 0;
  if (a.categoryId === b.categoryId) score += 2;
  const sharedInputs = a.inputFormats.filter(f => b.inputFormats.includes(f));
  score += sharedInputs.length * 3;
  const sharedOutputs = a.outputFormats.filter(f => b.outputFormats.includes(f));
  score += sharedOutputs.length * 3;
  const aInputInBOutput = a.inputFormats.filter(f => b.outputFormats.includes(f));
  score += aInputInBOutput.length * 2;
  const aOutputInBInput = a.outputFormats.filter(f => b.inputFormats.includes(f));
  score += aOutputInBInput.length * 2;
  const aFamilies = new Set(a.inputFormats.map(f => (FORMATS[f]?.family || "other")));
  const bFamilies = new Set(b.inputFormats.map(f => (FORMATS[f]?.family || "other")));
  for (const family of aFamilies) {
    if (bFamilies.has(family)) score += 1;
  }
  return score;
}

/** Build all tools and post-process (related links) */
function buildAll(): { tools: ToolDefinition[]; map: Map<string, ToolDefinition> } {
  const tools = allEntries.map(buildEntry);
  const map = new Map<string, ToolDefinition>(tools.map((t) => [t.slug, t]));

  // Post-process: compute related tool slugs using similarity scoring
  for (const tool of tools) {
    const scored = tools
      .filter((t) => t.slug !== tool.slug && !t.comingSoon)
      .map((t) => ({ tool: t, score: computeSimilarity(tool, t) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, 12)
      .map((s) => s.tool.slug);
    tool.relatedSlugs = scored;
  }

  return { tools, map };
}

// ── Compute at module init ──────────────────────────────────────

const { tools: allTools, map: toolMap } = buildAll();

// ── Public Accessors ────────────────────────────────────────────

export function getTool(slug: string): ToolDefinition | undefined {
  return toolMap.get(slug);
}

export function getAllTools(): ToolDefinition[] {
  return allTools;
}

export function getCuratedTools(): ToolDefinition[] {
  const curatedSlugs = new Set(registryEntries.map(e => e.slug));
  return allTools.filter(t => curatedSlugs.has(t.slug));
}


export function getPopularTools(limit?: number): ToolDefinition[] {
  const popular = allTools.filter((t) => t.popular && !t.comingSoon);
  return limit ? popular.slice(0, limit) : popular;
}

export function getToolsByCategory(categoryId: string): ToolDefinition[] {
  return allTools.filter((t) => t.categoryId === categoryId && !t.comingSoon);
}

export function getCategoryById(id: string): ToolCategory | undefined {
  return CATEGORY_MAP.get(id);
}

export function getCategoryByUrlSlug(urlSlug: string): ToolCategory | undefined {
  const catId = URL_TO_CATEGORY[urlSlug];
  return catId ? CATEGORY_MAP.get(catId) : undefined;
}

export function getRelatedTools(tool: ToolDefinition, limit = 6): ToolDefinition[] {
  return tool.relatedSlugs.slice(0, limit).map((slug) => toolMap.get(slug)).filter(Boolean) as ToolDefinition[];
}

export function getToolCount(): number {
  return toolMap.size;
}

/** Slugs for SSG at build time (curated + popular generated tools) */
export function getStaticToolSlugs(): { tool: string }[] {
  const curatedSlugs = registryEntries.filter((t) => !t.comingSoon).map((t) => ({ tool: t.slug }));
  const generatedSlugs = getPopularTools()
    .filter((t) => !registryEntries.some((c) => c.slug === t.slug))
    .map((t) => ({ tool: t.slug }));
  return [...curatedSlugs, ...generatedSlugs];
}

export function getCategoryTools(categoryId: string): ToolDefinition[] {
  return allTools.filter((t) => t.categoryId === categoryId && !t.comingSoon);
}

export function getCategoryStats(categoryId: string) {
  const tools = getCategoryTools(categoryId);
  const popular = tools.filter((t) => t.popular);
  const formats = new Set(tools.flatMap((t) => [...t.inputFormats, ...t.outputFormats]));
  return { total: tools.length, popular: popular.length, formats: formats.size };
}

export function getCategoryPopularTools(categoryId: string, limit = 6): ToolDefinition[] {
  return allTools.filter((t) => t.categoryId === categoryId && t.popular && !t.comingSoon).slice(0, limit);
}

export function getFormatByExt(ext: string): FormatDefinition | undefined {
  return FORMATS[ext];
}

export function getToolsByInputFormat(ext: string): ToolDefinition[] {
  return allTools.filter((t) => t.inputFormats.includes(ext) && !t.comingSoon);
}

export function getToolsByOutputFormat(ext: string): ToolDefinition[] {
  return allTools.filter((t) => t.outputFormats.includes(ext) && !t.comingSoon);
}

export function getToolsByFormat(ext: string): ToolDefinition[] {
  return allTools.filter((t) => (t.inputFormats.includes(ext) || t.outputFormats.includes(ext)) && !t.comingSoon);
}

// ── Convenience: get curated count (for tool cards) ─────────────

export function getCuratedToolCount(categoryId: string): number {
  return registryEntries.filter((t) => t.category === categoryId && !t.comingSoon).length;
}
